### ISSUE TITLE
Error en el type del census

### ISSUE THREAD

**Issue by albtinher** [Decide-Part-Utrera/decide-part-utrera-1#32]
Tras de los commmits realizados despues del 24 de noviembre se produce un error en relación con el type en el census el cual se indica que ya existe:

![Captura desde 2022-11-30 20-54-30](https://user-images.githubusercontent.com/91564050/204895374-b4c8eace-1adf-4102-ab93-1001986d7448.png)

**Generador:** Alba Tinajero Herrera
**Motivo de creaciçon de incidencia:** bug/ERROR
**Sección del código afectado:** census 
**Propuesta de Solución:** cambiar tipo de votaciones
**Prioridad estimada:** High

**Comment by mysInma** [comment]
Incidencia solucionada, se solucionó cambiando el modelo.
