### ISSUE TITLE
Error en en la creación de distintas votaciones

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#35]
![Image](https://user-images.githubusercontent.com/74002527/206918322-e05359c6-226e-4236-87d3-ec78e73f77b1.png)

Tras los problemas obtenidos para crear los diferentes tipos de votaciones, se ha optado por cambiar de incremento y uno de los incrementos nuevos ha sido crear una validación para el lenguaje ofensivo en las votaciones.

**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** voting
**Propuesta de Solución:** cambiar de incremento
**Prioridad estimada:** High

**Comment by albtinher** [comment]
Incidencia cerrada por resolución del mismo
