### ISSUE TITLE
Error en la visualización del modo claro-oscuro

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#42]
Problemas en la visualización del resultado de las votaciones ya que no se visualizaban las gráficas.
**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** visualizer
**Propuesta de Solución:** modificar el css
**Prioridad estimada:** Medium

**Comment by albtinher** [comment]
Incidencia cerrada por resolución del mismo
