### ISSUE TITLE
Error en la visualización del pie de página.

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#43]
![Captura desde 2022-12-10 11-50-36](https://user-images.githubusercontent.com/74002527/206852075-77c21130-f0df-4e4f-ba3e-5ad0eaf6d9c5.png)

Problemas en la visualización del pie de página debido que a la hora ver las gráficas con el resultado de las votaciones quedaba en medio de la página impidiendo la correcta visualización de ellas.
**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** visualizer
****Propuesta de Solución:**** modificar el css
**Prioridad estimada:** Low

**Comment by albtinher** [comment]
Incidencia cerrada por resolución del mismo
