### ISSUE TITLE
Error en la creación de los test de visualización incremento modo claro y oscuro.

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#46]
![Captura desde 2022-12-10 17-36-45](https://user-images.githubusercontent.com/74002527/206865319-4ed789f5-072b-4bee-bc39-56563afc93dc.png)

Problemas en la creación de los tests ya que se hacían de manera que la aplicación tuviera que estar ejecutada, y solamente hacía el test de un id especifico.
**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** visualizer
**Propuesta de Solución:** modificar los test de manera que no haga falta hacer runserver.
**Prioridad estimada:** Medium

**Comment by albtinher** [comment]
Incidencia cerrada por resolución del mismo
