### ISSUE TITLE
Reducción del número de miembros del grupo de desarrollo

### ISSUE THREAD

**Issue by mrivas10** [Decide-Part-Utrera/decide-part-utrera-1#49]
Abandono de dos miembros del proyecto: José Manuel Cuevas y Juan Carlos Morales.
Generador: Manuel Rivas Llamas
Motivo de creación de incidencia: Ambos aprobaron la asignatura en el examen de tercera convocatoria
Sección del código afectado: no procede
Propuesta de Solución: Era algo que se contemplaba al inicio del proyecto, por lo que no afecta gran parte del desarrollo de las funcionalidades de nuestro proyecto.
Prioridad estimada: Medium

**Comment by albtinher** [comment]
Incidencia cerrada
