### ISSUE TITLE
Error en la conexión.

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#50]
![Captura desde 2022-12-11 18-24-04](https://user-images.githubusercontent.com/74002527/206918756-611832eb-6781-41bf-87f8-db3d73cb333f.png)

Problemas con la conexión de la página ya que no dejaba empezar una votación por problemas de creación del localhost con un puerto no correspondiente.
**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** voting
**Propuesta de Solución:** crear otro localhost con el puerto correspondiente.
**Prioridad estimada:** High

**Comment by albtinher** [comment]
Incidencia cerrada
