### ISSUE TITLE
Eliminación de rama feature/botTelegram

### ISSUE THREAD

**Issue by mrivas10** [Decide-Part-Utrera/decide-part-utrera-1#52]
**Generador:** Manuel Rivas Llamas
**Motivo de creación de incidencia:** Al comenzar el desarrollo una rama quedó estancada, y se decidió comenzar de nuevo la programación del bot de Telegram en otra nueva llamada feature/botTelegram2, la cual es la definitiva
**Sección del código afectado:** bot Telegram
**Propuesta de Solución:** eliminar rama
**Prioridad estimada:** Low

**Comment by mysInma** [comment]
Incidencia solucionada.
