### ISSUE TITLE
Fallo en el despliegue en okteto

### ISSUE THREAD

**Issue by mysInma** [Decide-Part-Utrera/decide-part-utrera-1#58]
![image](https://user-images.githubusercontent.com/74002527/208293557-cd878477-f72d-4c9c-912e-513540a93653.png)

Problemas al crear el manifiesto de okteto y poder desplegar la aplicación.
**Generador:** Inmaculada Mayo Salvatierra
**Motivo de creación de incidencia:** bug/ERROR
**Sección del código afectado:** ninguno
**Propuesta de Solución:** no desplegar en okteto.
**Prioridad estimada:** Low

**Comment by albtinher** [comment]
Se llega a la conclusion que no se despliega en okteto
