### ISSUE TITLE
Fallo en el despliegue de VAGRANT

### ISSUE THREAD

**Issue by albtinher** [Decide-Part-Utrera/decide-part-utrera-1#60]
![WhatsApp Image 2022-12-18 at 11 42 24](https://user-images.githubusercontent.com/91564050/208293977-94a2b6e6-0134-4a4c-ab24-98c2eefede54.jpeg)
![WhatsApp Image 2022-12-18 at 11 42 23](https://user-images.githubusercontent.com/91564050/208294006-929b9a3d-c6cb-44f1-80b9-ec53fe26a0b0.jpeg)
![](https://cdn.discordapp.com/attachments/1031203924830601323/1053986944239022130/Captura_desde_2022-12-18_11-47-28.png)

Problemas durante el despliegue de Vagrant debido al requirements y el VagrantFile y poder desplegar la aplicación.
**Generador**: Alba Tinajero Herrera
**Motivo de creación de incidencia**: bug/ERROR
**Sección del código afectado**: vagrant
**Propuesta de Solución**: buscar los requirements que dan fallos e intentar encontrar la libreria del error.
**Prioridad estimada**: High

**Comment by mysInma** [comment]
Fallos solucionados, se han arreglado los requirements y el python.yml.
